FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app 
COPY ["ConversaoPeso.Web/ConversaoPeso.Web.csproj","/app/"]
RUN dotnet restore "/app/ConversaoPeso.Web.csproj"
COPY . .
WORKDIR "/app/"
RUN dotnet build "ConversaoPeso.Web/ConversaoPeso.Web.csproj" -c Release -o /app/build 

#FROM build AS publish 
#RUN dotnet publish "ConversaoPeso.Web.csproj" -c Release -o /app/publish 

#FROM mcr.microsoft.com/dotnet/sdk:6.0 AS final
WORKDIR /app 
EXPOSE 80 
EXPOSE 443 
#COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet","ConversaoPeso.Web.dll" ]